# Generated by Django 5.2.5 on 2025-10-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CmsSlider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cms_img",
                    models.ImageField(
                        upload_to="slide_img/", verbose_name="Изображение"
                    ),
                ),
                (
                    "cms_title",
                    models.CharField(max_length=200, verbose_name="Заголовок"),
                ),
                ("cms_text", models.CharField(max_length=200, verbose_name="Текст")),
            ],
            options={
                "verbose_name": "модель",
                "verbose_name_plural": "модели",
            },
        ),
    ]
