# Generated by Django 5.2.5 on 2025-10-22 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("predlogenie", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CmsSlider",
            new_name="Predlogenie",
        ),
    ]
