# Generated by Django 5.2.5 on 2025-10-22 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("predlogenie", "0002_rename_cmsslider_predlogenie"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="predlogenie",
            options={
                "verbose_name": "Предложение",
                "verbose_name_plural": "Предложения",
            },
        ),
    ]
