# Generated by Django 5.2.5 on 2025-10-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predlogenie", "0003_alter_predlogenie_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="predlogenie",
            name="cms_img",
            field=models.ImageField(
                upload_to="predlog_img/", verbose_name="Изображение"
            ),
        ),
    ]
