# Generated by Django 5.2.5 on 2025-10-31 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Experts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exp_img",
                    models.ImageField(
                        upload_to="experts_img/", verbose_name="Изображение"
                    ),
                ),
                (
                    "exp_title",
                    models.CharField(max_length=200, verbose_name="Заголовок"),
                ),
                ("exp_text", models.CharField(max_length=200, verbose_name="Текст")),
            ],
            options={
                "verbose_name": "Мастер",
                "verbose_name_plural": "Мастера",
            },
        ),
    ]
