# Generated by Django 5.2.5 on 2025-11-04 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StatusCrm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_name",
                    models.CharField(max_length=100, verbose_name="Название статуса"),
                ),
            ],
            options={
                "verbose_name": "статус",
                "verbose_name_plural": "статусы",
            },
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_dt",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                ("site_name", models.CharField(max_length=200, verbose_name="Имя")),
                ("site_email", models.EmailField(max_length=200, verbose_name="Email")),
                (
                    "site_phone",
                    models.CharField(max_length=200, verbose_name="Телефон"),
                ),
                (
                    "site_message",
                    models.TextField(max_length=250, verbose_name="Сообщение"),
                ),
                (
                    "site_status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="crm.statuscrm",
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "сообщение/заказ",
                "verbose_name_plural": "сообщения/заказы",
            },
        ),
    ]
