# Generated by Django 5.2.5 on 2025-10-20 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название компании"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="run.jpg",
                        upload_to="main/%Y/%m/%d/",
                        verbose_name="Логотип компании",
                    ),
                ),
                (
                    "demo_link",
                    models.CharField(
                        blank=True, max_length=2000, verbose_name="Ссылка"
                    ),
                ),
            ],
            options={
                "verbose_name": "компания",
                "verbose_name_plural": "компании",
            },
        ),
        migrations.CreateModel(
            name="Eco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True, default="run.jpg", upload_to="main/%Y/%m/%d/"
                    ),
                ),
                ("category", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=256, verbose_name="Название квартира"),
                ),
                ("address", models.CharField(max_length=200, verbose_name="Адрес")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=8, verbose_name="Цена"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "short_description",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Краткое описание"
                    ),
                ),
                (
                    "Area",
                    models.CharField(max_length=200, verbose_name="Площадь квартиры"),
                ),
                ("Floor", models.IntegerField(default=0, verbose_name="Этаж")),
                ("Parking", models.CharField(max_length=200, verbose_name="Парковка")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="run.jpg",
                        upload_to="main/%Y/%m/%d/",
                        verbose_name="Изображение квартиры",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.company",
                        verbose_name="Компания",
                    ),
                ),
            ],
            options={
                "verbose_name": "квартира",
                "verbose_name_plural": "квартиры",
            },
        ),
    ]
