# Generated by Django 5.2.5 on 2025-09-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Main",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, default="run.jpg", upload_to="main/%Y/%m/%d/"
                    ),
                ),
                ("demo_link", models.CharField(blank=True, max_length=2000)),
                ("uch", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("city", models.ManyToManyField(blank=True, to="main.city")),
            ],
        ),
    ]
