# Generated by Django 5.2.5 on 2025-10-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="year",
            field=models.IntegerField(default=0, verbose_name="Год постройки"),
        ),
    ]
