# Generated by Django 5.2.5 on 2025-09-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_main2"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, default="run.jpg", upload_to="main/%Y/%m/%d/"
                    ),
                ),
                ("demo_link", models.CharField(blank=True, max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=200)),
                ("Bedrooms", models.CharField(max_length=200)),
                ("Bathrooms", models.CharField(max_length=200)),
                ("Area", models.CharField(max_length=200)),
                ("Floor", models.CharField(max_length=200)),
                ("Parking", models.CharField(max_length=200)),
                (
                    "image",
                    models.ImageField(
                        blank=True, default="run.jpg", upload_to="main/%Y/%m/%d/"
                    ),
                ),
                ("Company", models.ManyToManyField(blank=True, to="main.company")),
            ],
        ),
    ]
