# Generated by Django 5.2.5 on 2025-09-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_company_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="money",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="room",
            name="Bathrooms",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="room",
            name="Bedrooms",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="room",
            name="Floor",
            field=models.IntegerField(default=0),
        ),
    ]
