# Generated by Django 5.2.5 on 2025-09-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_room_money_alter_room_bathrooms_alter_room_bedrooms_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="money",
            field=models.CharField(max_length=200),
        ),
    ]
