# Generated by Django 5.2.5 on 2025-10-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_room_money"),
    ]

    operations = [
        migrations.CreateModel(
            name="Eco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True, default="run.jpg", upload_to="main/%Y/%m/%d/"
                    ),
                ),
                ("category", models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name="main",
            name="city",
        ),
        migrations.DeleteModel(
            name="Main2",
        ),
        migrations.DeleteModel(
            name="City",
        ),
        migrations.DeleteModel(
            name="Main",
        ),
    ]
