# Generated by Django 5.2.5 on 2025-11-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "work_img",
                    models.ImageField(
                        upload_to="work_img/", verbose_name="Изображение"
                    ),
                ),
                (
                    "work_title",
                    models.CharField(max_length=200, verbose_name="Заголовок"),
                ),
                ("work_text", models.TextField(max_length=300, verbose_name="Текст")),
            ],
            options={
                "verbose_name": "Работа",
                "verbose_name_plural": "Работы",
            },
        ),
    ]
