# Generated by Django 5.2.5 on 2025-11-25 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("we_done", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Категория работ"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание категории"),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterField(
            model_name="work",
            name="work_img",
            field=models.ImageField(
                blank=True, upload_to="work_img/", verbose_name="Изображение"
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="work_text",
            field=models.TextField(blank=True, max_length=300, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="work",
            name="category",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="we_done.workcategory",
                verbose_name="Категория",
            ),
        ),
    ]
