# Generated by Django 5.2.5 on 2025-11-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("we_done", "0002_workcategory_alter_work_work_img_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="work_img",
            field=models.ImageField(upload_to="work_img/", verbose_name="Изображение"),
        ),
    ]
