# Generated by Django 5.2.5 on 2025-11-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("we_done", "0003_alter_work_work_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slider2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cms_img",
                    models.ImageField(
                        upload_to="slide_img/", verbose_name="Изображение"
                    ),
                ),
                (
                    "cms_title",
                    models.CharField(max_length=200, verbose_name="Заголовок"),
                ),
                ("cms_text", models.CharField(max_length=200, verbose_name="Текст")),
                (
                    "cms_css",
                    models.CharField(
                        default="-", max_length=20, verbose_name="CSS класс"
                    ),
                ),
            ],
            options={
                "verbose_name": "слайд",
                "verbose_name_plural": "слайды",
            },
        ),
    ]
