# Generated by Django 5.2.5 on 2025-11-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("we_done", "0004_slider2"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="slider2",
            options={
                "verbose_name": "слайд по работе",
                "verbose_name_plural": "слайды по работам",
            },
        ),
        migrations.RemoveField(
            model_name="slider2",
            name="cms_text",
        ),
        migrations.AlterField(
            model_name="slider2",
            name="cms_img",
            field=models.ImageField(
                upload_to="slide2_img/", verbose_name="Изображение"
            ),
        ),
    ]
