# Generated by Django 5.2.5 on 2025-11-30 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("we_done", "0005_alter_slider2_options_remove_slider2_cms_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="slider2",
            name="cms_cat",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="we_done.work",
                verbose_name="Название работы",
            ),
        ),
    ]
