# Generated by Django 5.2.5 on 2025-11-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("we_done", "0006_slider2_cms_cat"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="description",
            field=models.TextField(
                blank=True, max_length=1000, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="work_text",
            field=models.TextField(
                blank=True, max_length=300, verbose_name="Краткое Описание"
            ),
        ),
    ]
