# Generated by Django 5.2.5 on 2025-11-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField(default=0, verbose_name="Стоимость")),
                (
                    "price_img",
                    models.ImageField(
                        upload_to="price_img/", verbose_name="Изображение"
                    ),
                ),
                (
                    "price_title",
                    models.CharField(max_length=200, verbose_name="Заголовок"),
                ),
                (
                    "price_text",
                    models.CharField(
                        default="Art Beauty", max_length=200, verbose_name="Описание"
                    ),
                ),
            ],
            options={
                "verbose_name": "Цена",
                "verbose_name_plural": "Цены",
            },
        ),
    ]
