# Generated by Django 5.2.5 on 2025-11-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price_site", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8, verbose_name="Стоимость"
            ),
        ),
        migrations.AlterField(
            model_name="price",
            name="price_img",
            field=models.ImageField(
                blank=True, upload_to="price_img/", verbose_name="Изображение"
            ),
        ),
    ]
