# Generated by Django 5.2.5 on 2025-10-27 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="price_text",
            field=models.CharField(
                default="Art Beauty", max_length=200, verbose_name="Описание"
            ),
        ),
    ]
